name: citibike_feature_engineering_pipeline

on:
  schedule:
    - cron: '2 * * * *'  # Runs every hour
  workflow_dispatch:       # Allows manual trigger

jobs:
  feature-engineering:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Feature Engineering Script
        run: |
          PYTHONPATH=. python src/feature_pipeline.py
