name: citibike_inference_pipeline

on:
  workflow_run:
    workflows: ["citibike_feature_engineering_pipeline"]
    types:
      - completed
  workflow_dispatch:       # Allows manual trigger

jobs:
  inference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Inference Script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          PYTHONPATH=. python src/inference.py
